// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyToDo.Api.Context;

namespace MyToDo.Api.Migrations.MailMySql
{
    [DbContext(typeof(MailMySqlContext))]
    [Migration("20240331063455_add_user")]
    partial class add_user
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MyToDo.Api.Context.Mail.SysUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("avatar");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("DelFlag")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("del_flag");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_date");

                    b.Property<string>("LoginIp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("login_ip");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nick_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("sex");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserType")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.ToTable("sys_user");
                });
#pragma warning restore 612, 618
        }
    }
}
