// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyToDo.Api.Context;

namespace MyToDo.Api.Migrations.MailMySql
{
    [DbContext(typeof(MailMySqlContext))]
    partial class MailMySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MyToDo.Api.Context.Mail.MailTest", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint")
                        .HasColumnName("dept_id");

                    b.HasKey("UserId");

                    b.ToTable("mail_test");
                });
#pragma warning restore 612, 618
        }
    }
}
